using HearthStoneSimCore.Enums;
using HearthStoneSimCore.Tasks;

namespace HearthStoneSimCore.Enchants
{
    /// <summary>
    /// An enchantment, also known as a buff or debuff, is a special effect gained by a minion. Enchantments may be generated by spells,
    /// minion texts or abilities such as Battlecries, or other sources, may be temporary or permanent, and can have a range of effects.
    /// </summary>
    public class Enchantment
	{
	    public EnchantmentActivation Activation { get; set; } = EnchantmentActivation.BOARD;
	    //public Enchant Enchant { get; set; }
	    public TriggerType Trigger { get; set; }
        public ISimpleTask Task { get; set; }
    }

    public enum EnchantmentActivation
    {
        BATTLECRY,
        DEATHRATTLE,
        BOARD,
        HAND,
        DECK,
        SECRET_OR_QUEST,
        SPELL,
        WEAPON,
        SETASIDE,
        NONE
    }
}
